# Generated by Django 3.1 on 2020-08-26 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=14)),
                ('email', models.CharField(max_length=45)),
                ('dt_nasc', models.DateTimeField()),
                ('foto', models.ImageField(upload_to='')),
            ],
        ),
    ]
