# Generated by Django 3.1 on 2020-08-26 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='foto',
        ),
    ]
